[package]
name = "flappy_birds_together"
version = "0.1.0"
edition = "2021"

[dependencies]

ggez = "0.7.0"
rand = "0.8.5"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "client2"
path = "src/client2.rs"

[[bin]]
name = "server"
path = "src/server.rs"